---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  type: LoadBalancer
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-deployment
          image: lawrencejews/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8038
            initialDelaySeconds: 30
            timeoutSeconds: 1