---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8222
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-deployment
          image: lawrencejews/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8222

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8036
            initialDelaySeconds: 30
            timeoutSeconds: 1