---
apiVersion: v1
kind: Service
metadata:
  name: quest-service-svc
spec:
  ports:
    - targetPort: 8092
      port: 80
  selector:
    app: quest-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-service-app
  labels:
    app: quest-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quest-service
  template:
    metadata:
      labels:
        app: quest-service
    spec:
      containers:
        - name: quest-service
          image: lawrencejews/quest-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8092