eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/quest-rewards/**
        - id: users
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/users/**
        - id: quest-process
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/quests/**
        - id: rewards
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/rewards/**
